[build]
  functions = "netlify/functions"

[functions]
  "extract-mvv-perplexity" = { timeout = 30 }
  "extract-mvv" = { timeout = 30 }
  "verify-business-idea" = { timeout = 60 }
  "verify-business-idea-background" = { timeout = 900 }
  "start-async-task" = { timeout = 30 }
  "task-status" = { timeout = 30 }

[dev]
  port = 8888
  targetPort = 8888
  host = "0.0.0.0"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Max-Age = "86400"

[context.production.environment]
  NODE_ENV = "production"

[context.develop.environment]
  NODE_ENV = "development"