[build]
  functions = "netlify/functions"
  publish = "../frontend/dist"

[dev]
  command = "echo 'Netlify Dev Server'"
  port = 8888

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Max-Age = "86400"

[context.production.environment]
  NODE_ENV = "production"

[context.develop.environment]
  NODE_ENV = "development"